advarisk/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'', include('social_django.urls', namespace='social')),
    url(r'^quiz/', include('quiz.urls', namespace='quiz_detail')),
]

quiz/urls.py
from django.conf.urls import url
from quiz.views import QuestionView, QuizView

app_name = 'quiz'

urlpatterns = [
    url(r'^quiz_detail/$', QuizView.as_view(), name='quiz_detail'),
    url(r'^question/$', QuestionView.as_view(), name='question_detail'),
]

quiz/models.py
import uuid
from django.db import models

# Create your models here.


class Quiz(models.Model):
    """
    Quiz's model, works as a wrapper for the questions
    """
    quiz_id = models.UUIDField(default=uuid.uuid4)
    name = models.CharField(max_length=120, null=True, blank=True)
    description = models.CharField(max_length=220, null=True, blank=True)
    slug = models.SlugField()

    def __str__(self):
        return self.name


class Question(models.Model):
    question_text = models.CharField(max_length=120, null=True, blank=True)
    is_published = models.BooleanField(default=False)
    quiz = models.ForeignKey(Quiz, related_name='questions')

    def __str__(self):
        return "{content} - {published}".format(
            content=self.question_text, published=self.is_published)


class Answer(models.Model):
    """
    Answer's Model, which is used as the answer in Question Model
    """
    text = models.CharField(max_length=120, null=True, blank=True)
    is_valid = models.BooleanField(default=False)
    question = models.ForeignKey(Question, related_name='answers')

    def __str__(self):
        return self.text

quiz/views.py
from django.contrib import messages
from django.shortcuts import render, render_to_response
from django.views.generic import ListView
from .models import Question, Quiz


class QuizView(ListView):

    def get(self, request):
        quiz_objs = Quiz.objects.all()
        return render(request, 'quiz.html', {'quiz_objs': quiz_objs})

    def post(self, request):
        post_data = request.POST.dict()
        if 'modify_val' in post_data:
            modify_id = request.POST.getlist('quiz_id')
            modify_name = request.POST.getlist('quiz_name')
            modify_data = dict(zip(modify_id, modify_name))
            for id, new_name in modify_data.items():
                quiz_obj = Quiz.objects.filter(quiz_id=id)
                if quiz_obj.first().name != new_name:
                    quiz_obj.update(name=new_name)
                    messages.success(request, 'Quiz has been updated.')
            return self.get(request)
        new_data = request.POST.dict()
        quiz = new_data['quiz_name']
        description = new_data['quiz_des']
        if quiz is '' and description is '':
            messages.warning(request, 'Please enter some text')
            return self.get(request)
        Quiz.objects.create(name=quiz, description=description)
        messages.success(request, 'Quiz has been Inserted.')
        return self.get(request)


class QuestionView(ListView):

    def get(self, request):
        ques_objs = Question.objects.all()
        return render(request, 'question.html', {'ques_objs': ques_objs})

    def post(self, request):
        data = request.POST.dict()
        if 'question_text' not in data:
            messages.warning(request, 'Please Select a Question')
            ques_objs = Question.objects.all()
            return render(request, 'question.html', {'ques_objs': ques_objs})
        elif len(request.POST.getlist('question_text')) > 1:
            messages.warning(request, 'Please Select Only one Question')
            ques_objs = Question.objects.all()
            return render(request, 'question.html', {'ques_objs': ques_objs})
        else:
            question = data['question_text']
            return render_to_response('answer_form.html',
                                      {'question': question})

quiz/templates/answer_form.html
<html>
<head>
    <title>test</title>
     <script type="text/javascript">
     function load()
     {
          window.document.test.submit();
          return;
     }
     </script>
</head>
<body onload="load()">
<form name="test" method="post" action="https://django-test.advarisk.com">
    <input type="hidden" name="question" value="{{ question }}" />
</form>
</body>
</html>

quiz/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
	<title>{% block head_title %}ADVARISK{% endblock head_title %}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/todc-bootstrap/3.3.7-3.3.13/css/bootstrap.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/todc-bootstrap/3.3.7-3.3.13/css/bootstrap-theme.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>
<body>

  {% include 'navbar.html' %}

  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endfor %}
    </ul>
  {% endif %}

<div class="container">

  {% block style %}
  {% endblock %}

  {% block content %}
  {% endblock content %}
</div>

</body>
</html>

quiz/templates/home.html
{% extends "layout.html" %}

{% block content %}
	{% if user.is_authenticated %}
             <p class="display-4">Hello, {{ user.username }}</p>
	{% else %}
             <a class="lead" href="{% url 'login' %}">Log in</a>
	{% endif %}
{% endblock content %}

quiz/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<title>Google Signin</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
		<div class="container">
				<a class="navbar-brand" href="/">Django App</a>
		</div>
	</nav>
<br> <br>
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endfor %}
    </ul>
  {% endif %}

    <div class="container">
	    {% block content %}
	    {% endblock content %}
    </div>
</body>
</html>

quiz/templates/question.html
{% extends 'layout.html' %}
{% block head_title %}ADVARISK|Question{% endblock head_title %}
{% block style %}
<style>
  hr {
  border: none;
  border-top: 10px solid #6f6f6f;;
}
</style>
{% endblock %}

{% block content %}
<h2> Quiz </h2>
      <table class="table table-condensed" style="font-size:15px">
        <thead>
            <tr>
              <th>Quiz Name</th>
              <th>Question</th>
            </tr>
        </thead>
      <tbody>
            {% for ques in ques_objs %}
              <tr>
                    <td>{{ ques.quiz }}</td>
                    <td>{{ ques.question_text }}</td>
              </tr>

          {% endfor %}
      </tbody>
    </table>
<hr>

<h2> Question/Answer </h2>

<form class="form-horizontal"
      method="post"
      enctype="multipart/form-data"
      action="{% url 'quiz:question_detail'%}"
      class="collapse">
      {% csrf_token %}

    <table class="table table-condensed" style="font-size:15px">
      <thead>
          <tr>
            <th></th>
            <th>Question</th>
            <th></th>

          </tr>
      </thead>
    <tbody>
          {% for ques in ques_objs %}
            <tr>
                <td class="action-checkbox"><input type="checkbox" name="question_text" class="action-select" value="{{ ques.question_text }}"/></td>
                  <td>
                    <input type="text" class="form-control"  name="question" value="{{ ques.question_text }}"></input>
                  </td>
                  <td><button class="btn btn-default btn-sm" name="submit" title="Save Annual Income/Existing Emi">Get Answer</span>
                  </button></td>
            </tr>

        {% endfor %}
    </tbody>
  </table>
</form>


{% endblock content %}

quiz/templates/quiz.html
{% extends 'layout.html' %}
{% block head_title %}ADVARISK|Quiz{% endblock head_title %}
{% block content %}
<h2> Quiz </h2>
<form class="form-horizontal"
      method="post"
      enctype="multipart/form-data"
      action="{% url 'quiz:quiz_detail'%}"
      class="collapse">
      {% csrf_token %}

      <table class="table table-condensed" style="font-size:15px">
        <thead>
            <tr>
              <th>Quiz Name</th>
              <th>Quiz Description</th>
            </tr>
        </thead>
      <tbody>
            {% for quiz in quiz_objs %}
              <tr>
                    <td>
                      <input type="text" class="form-control"  name="quiz_name" value="{{ quiz.name }}"></input>
                    </td>
                    <td>{{ quiz.description }}</td>
              </tr>
              <input type="hidden" name="quiz_id" value="{{ quiz.quiz_id }}">
          {% endfor %}
      </tbody>
    </table>
    <div class="submit">
      <input type="hidden" name="modify_val" value="0">
  <button type="submit" name="submit" class="btn btn-primary">Modify Quiz Name</button>
</div>
</form>



<form id="add_new" method="post"
      action="{% url 'quiz:quiz_detail'%}"
      enctype="multipart/form-data">
      {% csrf_token %}
                <div class="col-lg-12">
                  <div class="form-group">
            <label for="customer_id" class="col-sm-5 col-form-label">Quiz Name</label>
            <div class="col-sm-4">
            <input type="text" class="form-control"  name="quiz_name" value="{{ name }}"></input>
            </div>      <div class="form-group">
                  <label for="customer_id" class="col-sm-5 col-form-label">Description</label>
                  <div class="col-sm-4">
                      <input type="text" class="form-control"  name="quiz_des" value="{{ description }}"></input>
                  </div>

      </div>
      <div class="submit">
          <input type="hidden" name="new_val" value="1">
        <button type="submit" name="submit" class="btn btn-primary">Add a New Quiz</button>
      </div>

</form>
{% endblock %}